// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOl2GNgvi1FO2vdoGvXuQQCvkZDS7t9z8',
    appId: '1:122885456437:web:8259fe664756d6850fe77c',
    messagingSenderId: '122885456437',
    projectId: 'tripmate-3f78b',
    authDomain: 'tripmate-3f78b.firebaseapp.com',
    storageBucket: 'tripmate-3f78b.firebasestorage.app',
    measurementId: 'G-SL13Q8R7BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7VCiC-LHXSHRq_CiddinWLC3FZyF94h4',
    appId: '1:122885456437:android:616ef7b166f6ba800fe77c',
    messagingSenderId: '122885456437',
    projectId: 'tripmate-3f78b',
    storageBucket: 'tripmate-3f78b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP5k4VCgnt14njDVLwO5NKJyfEl3wC85w',
    appId: '1:122885456437:ios:a3dbb84d624185c10fe77c',
    messagingSenderId: '122885456437',
    projectId: 'tripmate-3f78b',
    storageBucket: 'tripmate-3f78b.firebasestorage.app',
    iosClientId: '122885456437-39sjhpuqajlsn74jpfvm1lbqbda647qs.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP5k4VCgnt14njDVLwO5NKJyfEl3wC85w',
    appId: '1:122885456437:ios:a3dbb84d624185c10fe77c',
    messagingSenderId: '122885456437',
    projectId: 'tripmate-3f78b',
    storageBucket: 'tripmate-3f78b.firebasestorage.app',
    iosClientId: '122885456437-39sjhpuqajlsn74jpfvm1lbqbda647qs.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOl2GNgvi1FO2vdoGvXuQQCvkZDS7t9z8',
    appId: '1:122885456437:web:09cbcb638c1151d00fe77c',
    messagingSenderId: '122885456437',
    projectId: 'tripmate-3f78b',
    authDomain: 'tripmate-3f78b.firebaseapp.com',
    storageBucket: 'tripmate-3f78b.firebasestorage.app',
    measurementId: 'G-E4BMWSGDW0',
  );
}
