import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../domain/entities/generated_itinerary_item.dart';
import '../../providers/activity_provider.dart';
import '../../providers/place_provider.dart';
import '../../providers/smart_itinerary_provider.dart';
import '../../providers/trip_provider.dart';
import '../../providers/user_provider.dart';

class SmartItineraryScreen
    extends ConsumerStatefulWidget {
  final String tripId;

  const SmartItineraryScreen({
    super.key,
    required this.tripId,
  });

  @override
  ConsumerState<SmartItineraryScreen>
      createState() =>
          _SmartItineraryScreenState();
}

class _SmartItineraryScreenState
    extends ConsumerState<
        SmartItineraryScreen> {
  int _placesPerDay = 3;

  bool _generated = false;

   final Set<String> _selectedPlaceIds =
        {};
        
  String _itemKey(
    GeneratedItineraryItem item,
  ) {
    if (item.place.id.isNotEmpty) {
      return item.place.id;
    }

    return '${item.place.latitude}_${item.place.longitude}';
  }
  
  Future<void> _generate() async {
    final trip = await ref.read(
      tripByIdProvider(
        widget.tripId,
      ).future,
    );

    if (trip == null) {
      return;
    }

    final cities = await ref
        .read(placeRepositoryProvider)
        .searchCities(
          '${trip.destination}, '
          '${trip.country}',
        );

    if (cities.isEmpty) {
      if (!mounted) {
        return;
      }

      ScaffoldMessenger.of(context)
          .showSnackBar(
        const SnackBar(
          content: Text(
            'Could not find destination coordinates.',
          ),
        ),
      );

      return;
    }

    final city =
        cities.first;

    await ref
        .read(
          smartItineraryControllerProvider
              .notifier,
        )
        .generate(
          trip: trip,
          latitude:
              city.latitude,
          longitude:
              city.longitude,
          placesPerDay:
              _placesPerDay,
        );

    if (!mounted) {
      return;
    }

    final result = ref.read(
      smartItineraryControllerProvider,
    );

    if (result.hasValue) {
      final items =
          result.value ?? [];

      setState(() {
        _selectedPlaceIds
          ..clear()
          ..addAll(
            items.map(
              (item) =>
                  _itemKey(item),
            ),
          );

        _generated = true;
      });
    }
  }

  Future<void> _saveGenerated(
    List<GeneratedItineraryItem>
        items,
  ) async {
    if (items.isEmpty) {
      return;
    }

    for (final item in items) {
      await ref
          .read(
            activityControllerProvider
                .notifier,
          )
          .createActivity(
            tripId:
                widget.tripId,
            title:
                item.place.name,
            location:
                item.place.address ??
                    item.place.name,
            date:
                item.date,
            startTime:
                item.startTime,
            note:
                'Generated by Smart Planner',
            latitude:
                item.place.latitude,
            longitude:
                item.place.longitude,
            placeId:
                item.place.id,
          );

      final state = ref.read(
        activityControllerProvider,
      );

      if (state.hasError) {
        if (!mounted) {
          return;
        }

        ScaffoldMessenger.of(context)
            .showSnackBar(
          SnackBar(
            content: Text(
              'Failed to save itinerary: '
              '${state.error}',
            ),
          ),
        );

        return;
      }
    }

    ref.invalidate(
      activitiesProvider(
        widget.tripId,
      ),
    );

    if (!mounted) {
      return;
    }

    ScaffoldMessenger.of(context)
        .showSnackBar(
      const SnackBar(
        content: Text(
          'Smart itinerary saved.',
        ),
      ),
    );

    Navigator.of(context).pop();
  }

  @override
  Widget build(
    BuildContext context,
  ) {
    final tripAsync =
        ref.watch(
      tripByIdProvider(
        widget.tripId,
      ),
    );

    final generationState =
        ref.watch(
      smartItineraryControllerProvider,
    );

    final groupPreferencesAsync =
        ref.watch(
      tripGroupPreferencesProvider(
        widget.tripId,
      ),
    );

    return Scaffold(
      appBar: AppBar(
        title: const Text(
          'Smart Itinerary',
        ),
      ),

      body: tripAsync.when(
        loading: () =>
            const Center(
          child:
              CircularProgressIndicator(),
        ),

        error: (
          error,
          stackTrace,
        ) =>
            Center(
          child: Text(
            'Failed to load trip: $error',
          ),
        ),

        data: (trip) {
          if (trip == null) {
            return const Center(
              child:
                  Text(
                'Trip not found',
              ),
            );
          }

          return ListView(
            padding:
                const EdgeInsets.all(
              20,
            ),
            children: [
              Text(
                trip.title,
                style:
                    Theme.of(context)
                        .textTheme
                        .headlineSmall,
              ),

              const SizedBox(
                height: 6,
              ),

              Text(
                '${trip.destination}, '
                '${trip.country}',
              ),

              const SizedBox(
                height: 24,
              ),

              Text(
                'Group Preferences',
                style:
                    Theme.of(context)
                        .textTheme
                        .titleLarge,
              ),

              const SizedBox(
                height: 12,
              ),

              groupPreferencesAsync.when(
                loading: () =>
                    const LinearProgressIndicator(),

                error: (
                  error,
                  stackTrace,
                ) =>
                    const Text(
                  'Unable to load group preferences.',
                ),

                data: (result) {
                  if (result.rankedPreferences
                      .isEmpty) {
                    return const Text(
                      'No travel preferences selected yet.',
                    );
                  }

                  return Wrap(
                    spacing: 8,
                    runSpacing: 8,
                    children:
                        result.rankedPreferences
                            .map(
                              (
                                preference,
                              ) {
                                final score =
                                    result.scores[
                                            preference] ??
                                        0;

                                return Chip(
                                  label: Text(
                                    '$preference · $score',
                                  ),
                                );
                              },
                            )
                            .toList(),
                  );
                },
              ),

              const SizedBox(
                height: 28,
              ),

              Text(
                'Places per day',
                style:
                    Theme.of(context)
                        .textTheme
                        .titleMedium,
              ),

              Slider(
                value:
                    _placesPerDay
                        .toDouble(),
                min: 2,
                max: 4,
                divisions: 2,
                label:
                    '$_placesPerDay',
                onChanged: (
                  value,
                ) {
                  setState(() {
                    _placesPerDay =
                        value.round();
                  });
                },
              ),

              Text(
                '$_placesPerDay activities each day',
              ),

              const SizedBox(
                height: 24,
              ),

              ElevatedButton.icon(
                onPressed:
                    generationState
                            .isLoading
                        ? null
                        : _generate,
                icon:
                    generationState
                            .isLoading
                        ? const SizedBox(
                            width: 20,
                            height: 20,
                            child:
                                CircularProgressIndicator(
                              strokeWidth:
                                  2,
                              color:
                                  Colors.white,
                            ),
                          )
                        : const Icon(
                            Icons.auto_awesome,
                          ),
                label:
                    Text(
                  _generated
                      ? 'Generate Again'
                      : 'Generate Itinerary',
                ),
              ),

              const SizedBox(
                height: 28,
              ),

              generationState.when(
                loading: () =>
                    const SizedBox
                        .shrink(),

                error: (
                  error,
                  stackTrace,
                ) =>
                    Text(
                  'Generation failed: $error',
                ),

                data: (items) {
                  if (items.isEmpty) {
                    if (_generated) {
                      return Container(
                        width: double.infinity,
                        padding: const EdgeInsets.all(
                          20,
                        ),
                        child: const Column(
                          children: [
                            Icon(
                              Icons.check_circle_outline,
                              size: 48,
                            ),
                            SizedBox(
                              height: 12,
                            ),
                            Text(
                              'No new places found',
                              style: TextStyle(
                                fontWeight:
                                    FontWeight.bold,
                              ),
                            ),
                            SizedBox(
                              height: 6,
                            ),
                            Text(
                              'The recommended places may already be in your itinerary.',
                              textAlign:
                                  TextAlign.center,
                            ),
                          ],
                        ),
                      );
                    }

                    return const Text(
                      'Generate a smart itinerary to preview it here.',
                    );
                  }

                  return Column(
                    children: [
                      Row(
                        mainAxisAlignment:
                            MainAxisAlignment.spaceBetween,
                        children: [
                          Text(
                            '${_selectedPlaceIds.length} '
                            'of ${items.length} selected',
                            style: Theme.of(context)
                                .textTheme
                                .titleMedium,
                          ),

                          TextButton(
                            onPressed: () {
                              setState(() {
                                if (_selectedPlaceIds.length ==
                                    items.length) {
                                  _selectedPlaceIds.clear();
                                } else {
                                  _selectedPlaceIds
                                    ..clear()
                                    ..addAll(
                                      items.map(
                                        _itemKey,
                                      ),
                                    );
                                }
                              });
                            },
                            child: Text(
                              _selectedPlaceIds.length ==
                                      items.length
                                  ? 'Clear all'
                                  : 'Select all',
                            ),
                          ),
                        ],
                      ),

                      const SizedBox(
                        height: 12,
                      ),

                      ..._buildDays(
                        items,
                      ),

                      const SizedBox(
                        height: 24,
                      ),

                      SizedBox(
                        width: double.infinity,
                        child: ElevatedButton.icon(
                          onPressed:
                              _selectedPlaceIds.isEmpty
                                  ? null
                                  : () {
                                      final selectedItems =
                                          items.where(
                                        (item) {
                                          return _selectedPlaceIds
                                              .contains(
                                            _itemKey(
                                              item,
                                            ),
                                          );
                                        },
                                      ).toList();

                                      _saveGenerated(
                                        selectedItems,
                                      );
                                    },
                          icon: const Icon(
                            Icons.save_outlined,
                          ),
                          label: Text(
                            'Save ${_selectedPlaceIds.length} '
                            '${_selectedPlaceIds.length == 1 ? 'Place' : 'Places'}',
                          ),
                        ),
                      ),
                    ],
                  );
                },
              ),
            ],
          );
        },
      ),
    );
  }

  List<Widget> _buildDays(
    List<GeneratedItineraryItem>
        items,
  ) {
    final grouped =
        <DateTime,
            List<
                GeneratedItineraryItem>>{};

    for (final item in items) {
      final day = DateTime(
        item.date.year,
        item.date.month,
        item.date.day,
      );

      grouped.putIfAbsent(
        day,
        () => [],
      );

      grouped[day]!.add(
        item,
      );
    }

    final days =
        grouped.keys.toList()
          ..sort();

    return days.asMap().entries.map(
      (entry) {
        final dayNumber =
            entry.key + 1;

        final date =
            entry.value;

        final dayItems =
            grouped[date]!;

        return Card(
          margin:
              const EdgeInsets.only(
            bottom: 16,
          ),
          child: Padding(
            padding:
                const EdgeInsets.all(
              16,
            ),
            child: Column(
              crossAxisAlignment:
                  CrossAxisAlignment
                      .start,
              children: [
                Text(
                  'Day $dayNumber',
                  style:
                      const TextStyle(
                    fontSize: 18,
                    fontWeight:
                        FontWeight.bold,
                  ),
                ),

                const SizedBox(
                  height: 4,
                ),

                Text(
                  '${date.day}/'
                  '${date.month}/'
                  '${date.year}',
                ),

                const SizedBox(
                  height: 12,
                ),

                ...dayItems.map(
                  (item) {
                    final key =
                        _itemKey(item);

                    final selected =
                        _selectedPlaceIds.contains(
                      key,
                    );

                    return CheckboxListTile(
                      contentPadding:
                          EdgeInsets.zero,

                      value:
                          selected,

                      onChanged: (value) {
                        setState(() {
                          if (value == true) {
                            _selectedPlaceIds.add(
                              key,
                            );
                          } else {
                            _selectedPlaceIds.remove(
                              key,
                            );
                          }
                        });
                      },

                      secondary: CircleAvatar(
                        child: Text(
                          item.startTime,
                          style:
                              const TextStyle(
                            fontSize: 9,
                          ),
                        ),
                      ),

                      title: Text(
                        item.place.name,
                      ),

                      subtitle: Text(
                        item.place.address ?? '',
                      ),
                    );
                  },
                ),
              ],
            ),
          ),
        );
      },
    ).toList();
  }
}